// Generated by gencpp from file wheel_leg/wl_control.msg
// DO NOT EDIT!


#ifndef WHEEL_LEG_MESSAGE_WL_CONTROL_H
#define WHEEL_LEG_MESSAGE_WL_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheel_leg
{
template <class ContainerAllocator>
struct wl_control_
{
  typedef wl_control_<ContainerAllocator> Type;

  wl_control_()
    : linear_vel(0.0)
    , angular_vel(0.0)
    , leg_pos(0.0)  {
    }
  wl_control_(const ContainerAllocator& _alloc)
    : linear_vel(0.0)
    , angular_vel(0.0)
    , leg_pos(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_vel_type;
  _linear_vel_type linear_vel;

   typedef double _angular_vel_type;
  _angular_vel_type angular_vel;

   typedef double _leg_pos_type;
  _leg_pos_type leg_pos;





  typedef boost::shared_ptr< ::wheel_leg::wl_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheel_leg::wl_control_<ContainerAllocator> const> ConstPtr;

}; // struct wl_control_

typedef ::wheel_leg::wl_control_<std::allocator<void> > wl_control;

typedef boost::shared_ptr< ::wheel_leg::wl_control > wl_controlPtr;
typedef boost::shared_ptr< ::wheel_leg::wl_control const> wl_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheel_leg::wl_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheel_leg::wl_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wheel_leg::wl_control_<ContainerAllocator1> & lhs, const ::wheel_leg::wl_control_<ContainerAllocator2> & rhs)
{
  return lhs.linear_vel == rhs.linear_vel &&
    lhs.angular_vel == rhs.angular_vel &&
    lhs.leg_pos == rhs.leg_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wheel_leg::wl_control_<ContainerAllocator1> & lhs, const ::wheel_leg::wl_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wheel_leg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wheel_leg::wl_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheel_leg::wl_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheel_leg::wl_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheel_leg::wl_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheel_leg::wl_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheel_leg::wl_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheel_leg::wl_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fc1c80748cd92d4ec0e0172340cea1e";
  }

  static const char* value(const ::wheel_leg::wl_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fc1c80748cd92d4ULL;
  static const uint64_t static_value2 = 0xec0e0172340cea1eULL;
};

template<class ContainerAllocator>
struct DataType< ::wheel_leg::wl_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheel_leg/wl_control";
  }

  static const char* value(const ::wheel_leg::wl_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheel_leg::wl_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_vel  # 线速度\n"
"float64 angular_vel # 角速度\n"
"float64 leg_pos  # 腿关节位置\n"
;
  }

  static const char* value(const ::wheel_leg::wl_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheel_leg::wl_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_vel);
      stream.next(m.angular_vel);
      stream.next(m.leg_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wl_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheel_leg::wl_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheel_leg::wl_control_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_vel: ";
    Printer<double>::stream(s, indent + "  ", v.linear_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_vel: ";
    Printer<double>::stream(s, indent + "  ", v.angular_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "leg_pos: ";
    Printer<double>::stream(s, indent + "  ", v.leg_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEEL_LEG_MESSAGE_WL_CONTROL_H
